assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - IhswSecretBundle
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        # yui_js:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.7.jar
        #     apply_to: "\.js$"
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.7.jar
            apply_to: "\.css$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"